#!/bin/sh
cd "${0%/*}" || exit 1    # Run from this directory

# Parse arguments for library compilation
. "$WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments"

# Perform various checks
[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

wmake "$targetType" common
wmake "$targetType" libraries/porousMedia
wmake "$targetType" applications/modules/darcy
#wmake "$targetType" libraries/multiphasePorousMedia
#wmake "$targetType" applications/modules/multiphaseDarcy
