#!/bin/sh
cd "${0%/*}" || exit 1    # Run from this directory

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Set application name
application=$(getApplication)

runApplication blockMesh
runApplication "$application"
runApplication -s probes foamPostProcess -func probes
runApplication -s graphUniform foamPostProcess -func graphUniform

gnuplot "plot.gpl"

#------------------------------------------------------------------------------
